# See versions here: https://hub.docker.com/_/ubuntu/
FROM ubuntu:rolling

RUN apt-get update && apt-get install -y \
	subversion \
	sasl2-bin

#RUN useradd svn

COPY app/.bash_aliases /root

EXPOSE 3690
VOLUME /svn

CMD svnserve -d --foreground -r /svn --listen-port 3690 --log-file /var/log/svn.log
